# -*- coding: utf-8 -*-
"""ِAllam2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q9WUmyL6sYwu14gBCqxKyteW1FLsi3y9
"""

!pip install gradio duckduckgo-search transformers accelerate sentencepiece bitsandbytes --quiet

!pip install duckduckgo_search --upgrade --quiet

from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
from duckduckgo_search import DDGS

model_name = 'ALLAM-AI/ALLaM-7B-Instruct-preview'

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name, device_map='auto', trust_remote_code=True)

story_generator = pipeline("text-generation", model=model, tokenizer=tokenizer)

import pandas as pd
df = pd.read_csv('datasetAdvanced.csv')
df.head()

def get_site_and_generate_story(user_input, user_age):
    match = df[df['اسم الموقع'].str.contains(user_input, case=False, na=False)]

    if match.empty:
        return "❌ لم يتم العثور على موقع مطابق."

    site = match.iloc[0]
    site_name = site['اسم الموقع']
    description = site['الوصف']
    region = site['المنطقة']
    source = site['المصدر']

    if user_age == "أطفال":
        tone = "اكتب قصة قصيرة جدًا ..."
    elif user_age == "مراهقين":
        tone = "اكتب قصة قصيرة بلغة مشوقة ..."
    else:
        tone = "اكتب قصة واقعية بأسلوب أدبي ..."

    prompt = f"""
{tone}
الموقع: "{site_name}" - منطقة {region}
الوصف: {description}
المصدر: {source}
يرجى أن تكون القصة مأخوذة من مصادر موثوقة، وتتناسب مع الفئة المستهدفة ({user_age}).
ابدأ القصة الآن:
"""

    result = story_generator(
        prompt,
        max_length=150,
        temperature=0.7,
        top_p=0.95,
        repetition_penalty=1.1,
        do_sample=True,
        pad_token_id=tokenizer.eos_token_id,
        eos_token_id=tokenizer.eos_token_id
    )

    full_text = result[0]["generated_text"]
    story_only = full_text.replace(prompt, "").strip()

    print("✅ القصة:", story_only)

    return story_only

import gradio as gr

interface = gr.Interface(
    fn=get_site_and_generate_story,
    inputs=[
        gr.Textbox(label="🕌 أدخل جزء من اسم الموقع التراثي:"),
        gr.Dropdown(choices=["أطفال", "مراهقين", "بالغين"], label="👥 اختر الفئة العمرية", value=None)
    ],
    outputs=[
        gr.Textbox(label="📜 القصة", lines=15, max_lines=30, interactive=False)
        #gr.Image(label="🖼️ صورة الموقع")
    ],
    title="📖 استكشف التراث الثقافي السعودي",
    description="أدخل اسم موقع تراثي واختر الفئة العمرية، وسنحكي لك قصة مشوّقة ونريك صورة للموقع!"
)

interface.launch()